type = "card"
title = "Members"
description = "Our team of researchers and students."

[[items]]
title = "[Prof. Zhi Wang](https://www.mmlab.top/)"
subtitle = "Principal Investigator"
date = ""
content = "Tsinghua Shenzhen International Graduate School. Email: wangzhi@sz.tsinghua.edu.cn"
tags = ["Faculty"]

[[items]]
title = "[Yuan Meng](https://mengyuan404.github.io/)"
subtitle = "Faculty"
date = ""
content = "Department of Computer Science, Tsinghua University. Email: yuanmeng@tsinghua.edu.cn"
tags = ["Faculty"]

[[items]]
title = "[Ye Li](https://scholar.google.com/citations?user=Nof6bfUAAAAJ)"
subtitle = "PhD Student"
date = ""
content = "Email: liye23@mails.tsinghua.edu.cn"
tags = ["PhD Student"]

[[items]]
title = "[Kangye Ji](https://ky-ji.github.io)"
subtitle = "PhD Student"
date = ""
content = "Email: jky25@mails.tsinghua.edu.cn"
tags = ["PhD Student"]
