[[news]]
date = "2026-02"
content = "One paper accepted by CVPR 2026 ğŸ‰"

[[news]]
date = "2026-01"
content = "Two papers accepted by ICLR 2026 ğŸ‰"

[[news]]
date = "2025-10"
content = "One paper accepted by TPAMI ğŸ‰"
